name: CI Linux

# Trigger this workflow on push or pull request
on: [push, pull_request]

jobs:
  build:
    name: Build and test (ubuntu-20.04)

    runs-on: ubuntu-20.04

    env:
      CXXFLAGS: -std=c++2a
      LDFLAGS: -L/usr/local/lib

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libgl1-mesa-dev libgl-dev libx11-dev libxrandr-dev libudev-dev libopenal-dev libvorbis-dev libflac-dev libxcursor-dev

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ubuntu-20.04-RELEASE

    - name: CMake configure
      run: |
        cd build
        export LD_RUN_PATH="/opt/gcc-latest/lib64"
        cmake -GNinja -DCMAKE_BUILD_TYPE=RELEASE -DSSVOH_HEADLESS_TESTS=1 ..

    - name: Build
      run: ninja -C build

    - name: Copy artifacts
      run: |
        cp build/SSVOpenHexagon build/OHWorkshopUploader _RELEASE

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenHexagon-Linux
        path: _RELEASE

    - name: Run tests
      run: |
        mkdir -p build/test
        cp -R _RELEASE/Packs .
        cp -R _RELEASE/Packs build
        cp -R _RELEASE/Packs build/test
        ninja -C build check

    - name: Check ldd
      run: |
        ldd build/test/test.Replay.t
